### ISSUE TITLE
Babel Runtime Dependency

### ISSUE THREAD

**Issue by svozza** [CascadeEnergy/dynamoDb-marshaler#16]
Just wondering is there a particular reason why the babel runtime is a main dependency rather that a dev one? It increases the size of the package by nearly 6Mb when you download it on `npm`. While that normally doesn't matter server side it is a problem when using the library in AWS Lambda because startup time and execution speed are influenced by the size of the zip file you upload.

**Comment by nackjicholson** [comment]
My understanding at the time of publishing this was that with babel 5, in order to distribute libraries that could utilize es6 features without globally polyfilling a consuming environment, one could package the module with babel-runtime.

I will look into that because that does seem like a mistake.

May be worth considering either bumping to babel 6, and using webpack to bundle it as a commonjs module

OR just removing babel entirely and writing this module in compliance with only the features available in node. Either using es5 to maintain compatability with Node 0.10 and 0.12, or  bumping the engine dependency in package.json to Node 5 in order to use the supported es6 syntax.

**Comment by svozza** [comment]
I guess you could target the LTS version of Node but that would involve rewriting lots of stuff. I am sure there are ways just to import the bits of Babel that you actually need.

**Comment by svozza** [comment]
So I've been playing around with this tonight, with a few tweaks you could use `rollup` to package the project. I've managed to get it building locally by using `lodash-es` and making the same change in `dispatch-recursive`. I also had to add the `jsnext:main` property to the latter's `package.json`. I'm happy to pursue this further and submit PRs to both projects if you want. One problem I'm having is trying to get `gulp-mocha` to work with Babel 6. It's just reinforced my view that these build tools are more hassle than they're worth: I could have had this done on the command line in 2 minutes rather than the two hours I've spent without success.

**Comment by nackjicholson** [comment]
Yeah, I'm on the same page. The build tools are complicating this module. Using them was an exercise in learning them. Now that I've done that, I think they're really useful for front-end applications, but not as well suited to distribution of npm modules.

You can continue messing around with this if you'd like. I'm not sure when I'll get to it, but my tentative plan is to just rip out gulp, babel, and everything, port this project and dispatch-recursive back to 0.10 compliant node.js and call it good.

Thanks for the help in pointing this out, thanks for any code you produce as a result, and generally thanks for putting some time into it.

**Comment by svozza** [comment]
No problem, this was a nice chance for me to play around with Babel and Rollup, I don't do any frontend development so it's rare that I get to use these tools. That said, I see where you're coming from with targeting Node 0.10. I'd be happy to help with that rewrite if you'd prefer, I like this module and it was a shame that I had to replace it with something else for our lambda functions.

**Comment by svozza** [comment]
Given https://github.com/CascadeEnergy/dispatch-recursive/pull/4, would you accept a PR that rewrote this in ES5?

**Comment by nackjicholson** [comment]
#17 In progress

**Comment by svozza** [comment]
Fixed as part of #17
