### ISSUE TITLE
Error: Encountered unexpected item

### ISSUE THREAD

**Issue by viquanghoa** [CascadeEnergy/dynamoDb-marshaler#21]
I have a problem when using dynamoDB, the error content : "Encountered unexpected item". 
Please help me fix bug above.

**Comment by viquanghoa** [comment]
I detect your libs has some problem with my input.
Detail is:
[ { field1: 'ブラック', field2: 2005, **field3: ''**, field4: 35000, field5: 798000 } ]
Bug report: Encountered unexpected item.
I debug see problem from **field3** is blank.

**Comment by articice** [comment]
Same problem here, for a valid input.

**Comment by viquanghoa** [comment]
> Same problem here, for a valid input

I detect problem because AWS DynamoDB not allow empty string.
Please read here https://github.com/CascadeEnergy/dynamoDb-marshaler#understanding-the-rules

**Comment by articice** [comment]
Right, had to fix it elsewhere.

**Comment by nwarlen** [comment]
This library has not been updated in some time. I would recommend using the officially supported document client from AWS. http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

Let me know if you would like more information.
