### ISSUE TITLE
Don't deprecate - yet

### ISSUE THREAD

**Issue by cmawhorter** [CascadeEnergy/dynamoDb-marshaler#23]
I (still) use ddb-marshaler to process [streams](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html) which come through in the ddb format.  

DocumentClient does not expose a mechanism for translating arbitrary data to ddb's format and back, so this lib is my only option AFAIK.

Don't deprecate it quite yet?

**Comment by mvayngrib** [comment]
ditto

**Comment by cberube** [comment]
The `AWS.DynamoDB.Converter` module might have the functionality you're looking for:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/Converter.html

**Comment by cmawhorter** [comment]
and here i am thinking i thoroughly combed the docs.  closing.
