### ISSUE TITLE
use this library without node or npm

### ISSUE THREAD

**Issue by gagecarto** [CascadeEnergy/dynamoDb-marshaler#7]
I am a total noob when it comes to node and npm. Is there a way I could use this library without node? Could I load the library purely using html and js and then call the functions (especially unmarshal) in my js code?

**Comment by nackjicholson** [comment]
There is not currently a browser distribution of this project, sorry. You might look into a node module called http://browserify.org/ which can take node.js code and bundle it for use in the browser. This isn't a promise, as I've never looked into it, but you might be able to download this repo, run `$ browserify index.js > dynamodb-marshaler-dist.js`

And then you can do `<script type='text/javascript' src='dynamodb-marshaler-dist.js'></script>`

Thanks for the issue! Let me know if you can get this working in the browser, I'll keep the issue around as a reminder to make a client side distribution.

**Comment by nackjicholson** [comment]
I made a browser distribution of this. It's at `dist/dynamodb-marshaler.js` in this repo.

There is an example of how to use it here at [examples/example.html](https://github.com/CascadeEnergy/dynamoDb-marshaler/blob/master/examples/example.html)

You can run it in your browser or you can check it out at this plunkr http://embed.plnkr.co/djI2cuXAqssYZoHO9s5a/preview
