### ISSUE TITLE
Unable to unmarshal string set

### ISSUE THREAD

**Issue by jinsyaoommen** [CascadeEnergy/dynamoDb-marshaler#9]
When I unmarshal the following:
```
{ foo: { SS: [ 'foo1', 'foo2' ] } }
```
I get `{ foo: {} }`

**Comment by nackjicholson** [comment]
Thanks. Yeah, ewww...looks like a regression from when I switched to ES6 Sets.

**Comment by koresar** [comment]
This regression is what I have spent few hours today debugging. :) Not pushing.

Add tests on that case please.

**Comment by nackjicholson** [comment]
@koresar +1 Needs to be fixed and it will be.

https://www.youtube.com/watch?v=J8ZFxsq9-3k

http://www.urbandictionary.com/define.php?term=Sorry+Not+Sorry

**Comment by nackjicholson** [comment]
Rolled out as part of patch fix `v1.1.3`

Thanks for bringing it to my attention, sorry about the problems.
